@echo off
echo Starting Backend...
cd backend
if not exist venv\Scripts\python.exe (
    echo Creating virtual environment...
    python -m venv venv
)

echo Activating virtual environment...
call venv\Scripts\activate.bat

echo Installing dependencies...
venv\Scripts\python.exe -m pip install -r requirements.docker.txt

echo Starting uvicorn...
venv\Scripts\python.exe -m uvicorn main:app --reload
